// <auto-generated />

using System.Diagnostics.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using {{cookiecutter.ProjectName}}.Persistence;

#nullable disable

namespace {{cookiecutter.ProjectName}}.Persistence.Migrations
{
    [ExcludeFromCodeCoverage]
    [DbContext(typeof({{cookiecutter.ProjectName}}DbContext))]
    partial class {{cookiecutter.ProjectName}}DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("{{cookiecutter.ProjectName}}.Persistence.DAO.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("IfscCode")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("IfscCode");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("IfscCode")
                        .IsUnique();

                    b.ToTable("Bank");
                });
#pragma warning restore 612, 618
        }
    }
}
