ConnectionStrings:
  Postgres: "Server=127.0.0.1;Port=5432;User Id=postgres;Password=postgres;Database={{cookiecutter.ProjectName}};Timeout=300;"
LogstashConfiguration:
  Enabled: false
Serilog:
  MinimumLevel:
    Default: Debug
    Override:
      Microsoft: Warning
      System: Warning
