version: '3.7'

services:
    postgres:
        container_name: postgres
        image: postgres:14.1-alpine
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB={{cookiecutter.ProjectName}}
        ports:
            - '5432:5432'
        volumes:
            - db:/var/lib/postgresql
        networks:
            - {{cookiecutter.ProjectName}}network
    configserver:
        container_name: configserver
        image: hyness/spring-cloud-config-server
        ports:
            - "8888:8888"
        volumes:
            - ./configserver/config:/config
        environment:
            - SPRING_PROFILES_ACTIVE=native
            - SPRING_SECURITY_USER_NAME=${Spring_Cloud_Config_Username_VAL}
            - SPRING_SECURITY_USER_PASSWORD=${Spring_Cloud_Config_Password_VAL}
        networks:
            - {{cookiecutter.ProjectName}}network
volumes:
    db:
